#ifndef MONSTERS_H 
#define MONSTERS_H

typedef enum {
    NULL_MONSTER_TYPE,
    RAT,
    GOBLIN_WARRIOR,
	KOBOLD_WARRIOR,
    HOBGOBLIN,
    GOBLIN_RANGER,
    SKELETON_WARRIOR,
    SKELETON_ARCHER,
    MONSTER_END
} Monsters;

typedef enum {
    NULL_NPC_TYPE,
    NPC_RAT,
    NPC_GOBLIN_WARRIOR,
	NPC_KOBOLD_WARRIOR,
    NPC_HOBGOBLIN,
    NPC_GOBLIN_RANGER,
    NPC_SKELETON_WARRIOR,
    NPC_SKELETON_ARCHER,
    NPC_END
} NPCs;

#endif